# # kindly generated by appropriated Rails generator
# Mailjet.configure do |config|
#   config.api_key = ENV['MAILJET_LOGIN']
#   config.secret_key = ENV['MAILJET_PWD']
#   # config.api_key = 229389ec0ca1dbe0b4f44bb104329ed6
#   # config.secret_key = 7547df89bc045b3e3a889e60a5b1348a
#   #config.default_from = 'sarra.bouras@yahoo.com'
#   config.default_from = 'in-v3.mailjet.com'
#   # Mailjet API v3.1 is at the moment limited to Send API.
#   # We’ve not set the version to it directly since there is no other endpoint in that version.
#   # We recommend you create a dedicated instance of the wrapper set with it to send your emails.
#   # If you're only using the gem to send emails, then you can safely set it to this version.
#   # Otherwise, you can remove the dedicated line into config/initializers/mailjet.rb.
#   #config.api_version = 'v3.1'
# end

Mailjet.configure do |config|
  config.api_key = '229389ec0ca1dbe0b4f44bb104329ed6'
  config.secret_key = '7547df89bc045b3e3a889e60a5b1348a'
  config.default_from = 'philippediollot@hotmail.fr'
  #config.default_from = 'in-v3.mailjet.com'
  config.api_version = 'v3.1'
end